---
title: "Lecture: 06/08"
output: html_document
date: '2022-06-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(Lahman)
```

```{r}
Batting <- as_tibble(Batting)

head(Batting)
dim(Batting)
class(Batting)

apply(Batting, MARGIN = 2, FUN = class)
```

```{r}
summary(Batting)

table(Batting$lgID)

is.na(Batting$lgID) %>% sum()
```

```{r}
mlb_batting = filter(Batting, lgID %in% c("AL", "NL"))
```

```{r}
sel_batting = select(Batting, yearID, lgID, G, AB, R, H, HR, BB, SO)
```

```{r}
Batting %>%
  arrange(-HR)

Batting %>%
  summarise(max(stint), median(AB))

new_batting =  Batting %>%
  mutate(batting_avg = H/AB)
```

```{r}
Batting %>%
  filter(lgID %in% c("AL", "NL"), 
         AB > 300) %>%
  mutate(batting_avg = H/AB) %>%
  arrange(-batting_avg) %>%
  select(playerID, yearID, batting_avg) %>%
  slice(c(1, 3, 5))

Batting %>%
  filter(lgID %in% c("AL", "NL"), 
         AB > 300) %>%
  group_by(yearID) %>%
  summarise(hr = sum(HR), so = sum(SO), bb = sum(BB)) %>%
  arrange(-hr) %>%
  slice(1:5)
```

```{r}
year_batting_summary = Batting %>%
   filter(lgID %in% c("AL", "NL")) %>%
  group_by(yearID) %>%
  summarise(total_hits = sum(H, na.rm = T),
            total_hr = sum(HR, na.rm = T),
            total_so = sum(SO, na.rm = T),
            total_walks = sum(BB, na.rm = T),
            total_ab = sum(AB, na.rm = T)) %>%
  mutate(batting_avg = total_hits/total_ab)
```

```{r}
library(gt) #alternative to kableExtra

year_batting_summary %>%
  select(Year = yearID, "Batting AVG" = batting_avg) %>%
  arrange(desc("Batting AVG")) %>%
  slice(c(1:3, (n() - 2):n())) %>%
  gt() %>%
  tab_header(title = "Best/Worst MLB seasons by Batting AVG",
             subtitle = "Top/Bottom are presented")
```






















