---
title: "Untitled"
output: html_document
date: '2022-06-09'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#view basic git commands
library(magick)

image_read('https://static.javatpoint.com/tutorial/git/images/git-pull2.png') %>% print()
```

```{r}
#Configure Git
usethis::use_git_config(user.name = "Donald Dinerman", user.email = "ddinerma@andrew.cmu.edu")
```

```{r}
#Personal Access Token: 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
usethis::create_github_token()
```

```{r}
#enter token (2: replace these creds)
gitcreds::gitcreds_set()

# It should display the following info - 
# ? Enter password or token: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# -> Adding new credentials...
# -> Removing credentials from cache...
# -> Done.
```

Issue: Not connecting to my github account even after using new token, after changing repo visibility status (priv-->pub)

```{r}
#remote: Permission to Donald-Dinerman/Optum-Bridge-Summer-Research.git denied to Donald-Dinerman.
#fatal: unable to access 'https://github.com/Donald-Dinerman/Optum-Bridge-Summer-Research/': 
#The requested URL returned error: 403
```

